### ISSUE TITLE
请教FixWeixinBugWeixinResult 抛出 错误的原有和解决办法

### ISSUE THREAD

**Issue by 149392914** [JeffreySu/WeiXinMPSDK#1100]
##### 问题描述
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLC3PE609JEA", Request id "0HLC3PE609JEA:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Senparc.Weixin.MP.MvcExtension.FixWeixinBugWeixinResult.<ExecuteResultAsync>d__6.MoveNext()

如上代码所示，FixWeixinBugWeixinResult会抛出InvalidOperationException。
我用的版本是14.3.137
这个是在什么情况下会发生，和 当前是否已经有了解决办法，谢谢。

**Comment by JeffreySu** [comment]
有没有最小可用Demo？可以发我一下：www.jeffrey.su@gmail.com

**Comment by John0King** [comment]
@149392914 
> Headers are read-only, response has already started.

你是不是有什么中间件已经 进行 `Response.Write` 了？  一旦 Kestrel 开始向客户端发送数据， 你就不能再设置Header 或者 cookie 了

**Comment by 149392914** [comment]
没有最小可用Demo，最终定位到在扫码的时候在日志中会出现这个错误。@JeffreySu

**Comment by 149392914** [comment]
@John0King 只有一个customerHandler，其中处理Text，Image的都没有问题，目前就是在扫码的时候出现。

**Comment by JeffreySu** [comment]
有request xml可以给一下吗？如果加密的话需要给一下解密的资料。

**Comment by 149392914** [comment]
抱歉，因为在引用nuget包的时候没仔细看，引用的是非官方的包 Senparc.Weixin.MP.MvcExtension，因为名字很官方，并且是很早之前引用，所以一直没发现。
感谢两位的回复。
各位看官也引以为戒。

**Comment by JeffreySu** [comment]
@John0King 谢谢！
@149392914 OK
