### ISSUE TITLE
.NET Core 2.0 WeixinTrace 日志跟踪 报 系统找不到指定的文件。

### ISSUE THREAD

**Issue by DFvictor** [JeffreySu/WeiXinMPSDK#1243]
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 系统找不到指定的文件。
  Source=Senparc.Weixin
  StackTrace:
   at Senparc.Weixin.HttpUtility.Get.GetJson[T](String url, Encoding encoding, Nullable`1 maxJsonLength) in C:\project\Source\Workspaces\mobile\WeChat\Senparc.Weixin\Senparc.Weixin\Utilities\HttpUtility\Get.cs:line 135
   at Senparc.Weixin.Work.CommonAPIs.CommonApi.GetToken(String corpId, String corpSecret) in C:\project\Source\Workspaces\mobile\WeChat\Senparc.Weixin.Work\Senparc.Weixin.Work\CommonAPIs\CommonApi.cs:line 78
   at Senparc.Weixin.Work.Containers.AccessTokenContainer.GetTokenResult(String appKey, Boolean getNewToken) in C:\project\Source\Workspaces\mobile\WeChat\Senparc.Weixin.Work\Senparc.Weixin.Work\Containers\AccessTokenContainer.cs:line 263
   at Senparc.Weixin.Work.Containers.AccessTokenContainer.GetToken(String corpId, String corpSecret, Boolean getNewToken) in C:\project\Source\Workspaces\mobile\WeChat\Senparc.Weixin.Work\Senparc.Weixin.Work\Containers\AccessTokenContainer.cs:line 223
   at Senparc.Weixin.Work.Containers.AccessTokenContainer.TryGetToken(String corpId, String corpSecret, Boolean getNewToken) in C:\project\Source\Workspaces\mobile\WeChat\Senparc.Weixin.Work\Senparc.Weixin.Work\Containers\AccessTokenContainer.cs:line 199
   at CAFSG.Work.WeiXin.Models.WorkWeiXinSettings.get_access_token() in C:\project\Source\Workspaces\mobile\WeChat\CAFSG.Work.WeiXin\Models\WorkWeiXinSettings.cs:line 20

![image](https://user-images.githubusercontent.com/28973835/41573995-1018cdcc-73b2-11e8-9b2e-d22d946d88bd.png)

**Comment by JeffreySu** [comment]
用的 .net 版本是多少？

PS：请尽量按照默认格式要求填写issue。

**Comment by DFvictor** [comment]
##### .NET Core 2.0 

1. Senparc.Weixin.Config.IsDebug = true;
//negut上直接引用的最新包，设置IsDebug为true后，调试就报如下异常，不设置就一切正常并能正确需要的微信信息

详细
![image](https://user-images.githubusercontent.com/28973835/41582195-8005a422-73d3-11e8-93f8-f0c0bc487769.png)


![image](https://user-images.githubusercontent.com/28973835/41581830-69b72c8c-73d2-11e8-945e-ba74bf8085d0.png)

![image](https://user-images.githubusercontent.com/28973835/41581924-c61ba7aa-73d2-11e8-820c-3a3745f25bab.png)




##### 发现问题的模块

- [x] Senparc.Weixin 版本：


##### 模块对应的.net版本

- [x] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by DFvictor** [comment]
抱歉，已解决，是未设置Senparc.Weixin.Config.RootDictionaryPath的原因

**Comment by lishewen** [comment]
Senparc.Weixin.Config.RootDictionaryPath 给值
建文件夹 /App_Data/WeixinTraceLog/

@JeffreySu 这里有Bug，isDebug参数不生效
https://github.com/JeffreySu/WeiXinMPSDK/blob/f4f79ef89b2ff93f6debf91a2b1f535d98db64b2/src/Senparc.Weixin/Senparc.Weixin/RegisterServices/RegisterService.cs#L65

**Comment by JeffreySu** [comment]
@lishewen 已经在 CO2NET v0.1.1 中修复此问题。

@DFvictor  关于 RootDictionaryPath 设置，请参考Demo：https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L95

**Comment by JeffreySu** [comment]
@DFvictor CO2NET 中的注册参考这里：https://github.com/JeffreySu/WeiXinMPSDK/blob/Developer-CO2NET/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L95
