### ISSUE TITLE
AccessTokenContainer获取token时显示DI异常

### ISSUE THREAD

**Issue by LGinC** [JeffreySu/WeiXinMPSDK#1321]
`string token = await Senparc.Weixin.Work.Containers.AccessTokenContainer.TryGetTokenAsync(AppId, Secret);`

日志：
ERROR 2018-07-26 14:01:10,580 [54   ] Mvc.ExceptionHandling.AbpExceptionFilter - The type initializer for 'Nested' threw an exception.
System.TypeInitializationException: The type initializer for
 'Nested' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: services
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider
 (IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetServiceProvider()
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
   at Senparc.Weixin.Containers.BaseContainer`1.get_Cache()
   at Senparc.Weixin.Containers.BaseContainer`1.CheckRegistered(String shortKey)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.TryGetAccessTokenAsync(String appId, String appSecret, Boolean getNewToken)

Senparc.Weixin.Work版本 2.1.1

运行环境: .net core 2.1    WinServer2012 IIS8

**Comment by LGinC** [comment]
Senparc.Weixin.Work 2.0.6和1.6.0也会出现这个问题

**Comment by JeffreySu** [comment]
@LGinC 是不是没有进行Demo中的注册？

https://github.com/JeffreySu/WeiXinMPSDK/blob/2d305099794fe988d89098f1865588c746546172/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L102

**Comment by qibunext** [comment]
```c#
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
                                                        .UseSenparcGlobal(false, () => GetExCacheStrategies(senparcSetting.Value));
我加了下面这句，配置文件也加了还是报错
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)

//CO2NET 设置
  "SenparcSetting": {
    //以下为 CO2NET 的 SenparcSetting 全局配置，请勿修改 key，勿删除任何项

    "IsDebug": true,
    "DefaultCacheNamespace": "DefaultCache",
    //分布式缓存
    //"Cache_Redis_Configuration": "Redis配置",
    "Cache_Redis_Configuration": "127.0.0.1:6379,ssl=false,abortConnect=false,ConnectTimeout=10000,password=668comnet,keepAlive=10,syncTimeout=10000",
    "Cache_Memcached_Configuration": "Memcached配置",
    "SenparcUnionAgentKey": "SenparcUnionAgentKey"
  },
```

**Comment by JeffreySu** [comment]
UseSenparcGlobal()加了吗？

**Comment by qibunext** [comment]
@JeffreySu 没有加，参数可以不加吧？

**Comment by qibunext** [comment]
```
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
                                                        .UseSenparcGlobal();
```
这样写可以吗？

**Comment by JeffreySu** [comment]
@qibunext  这样可以。

**Comment by qibunext** [comment]
```
---------------------
时间：7/30/18 11:29:05 PM
详细信息:
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: services
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetServiceProvider()
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
   at Senparc.Weixin.Containers.BaseContainer`1.get_Cache()
   at Senparc.Weixin.Containers.BaseContainer`1.CheckRegistered(String shortKey)
   at Qibu.Controllers.WxMsgController.Msgs(String openId, String content, String MsgType, String username)
   at Qibu.Controllers.WxMsgController.Msg(String appid, String signature, String timestamp, String nonce, String echostr, String openid)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
----------------------------------------------------------------

/wxmsg/msg?signature=f30e4156642235f66745781a41c9d8f1cb737c60&timestamp=1532964545&nonce=807178148&openid=ohBDjs50u8mjbAOCc6YNRhXn1tE4
```

**Comment by JeffreySu** [comment]
@qibunext oh，那你可能是另外一个问题，这句没加2：

https://github.com/JeffreySu/WeiXinMPSDK/blob/1d71e1032cb03cd746da8b844612ef7b782f60ce/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L51

**Comment by qibunext** [comment]
```
---------------------
时间：7/30/18 11:42:27 PM
详细信息:
Senparc.CO2NET.Exceptions.UnregisteredDomainCacheStrategyException: 当前扩展缓存策略没有进行注册：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，Senparc.CO2NET.Cache.LocalObjectCacheStrategy
   at Senparc.CO2NET.Cache.CacheStrategyDomainWarehouse.GetDomainExtensionCacheStrategy(IBaseObjectCacheStrategy baseObjectCacheStrategy, ICacheStrategyDomain cacheStrategyDomain)
   at Senparc.Weixin.Containers.BaseContainer`1.get_Cache()
   at Senparc.Weixin.Containers.BaseContainer`1.CheckRegistered(String shortKey)
   at Qibu.Controllers.WxMsgController.Msgs(String openId, String content, String MsgType, String username)
   at Qibu.Controllers.WxMsgController.Msg(String appid, String signature, String timestamp, String nonce, String echostr, String openid)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

```

**Comment by qibunext** [comment]
可以了 .UseSenparcGlobal(true);  这样是不用分存式缓存是吧？

**Comment by DhoopuX** [comment]
请问一下，在控制台项目中怎么处理？谢谢.

**Comment by JeffreySu** [comment]
@qibunext 这样和用不用没关系。注册完了随时可以用，也可以一直不用。

**Comment by JeffreySu** [comment]
@DhoopuX  是.net core项目还是.net framework项目？

**Comment by DhoopuX** [comment]
用的是 netcore 的控制台项目中.冒昧的问一下，netcore 项目里怎么注册...谢谢
