### ISSUE TITLE
NeuChar在DI的时候异常：ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by OrchesAdam** [JeffreySu/WeiXinMPSDK#1406]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
根据案例的代码
在实例化CustomMessageHandler的时候抛出
```
public  CustomMessageHandler(XDocument requestDocument, PostModel postModel = null, int maxRecordCount = 0) : base(requestDocument, postModel, maxRecordCount)
```
```
Parameter name: services
Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)

TypeInitializationException: The type initializer for 'Nested' threw an exception.
Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()

TypeInitializationException: The type initializer for 'Senparc.NeuChar.Register' threw an exception.
Senparc.NeuChar.Register.RegisterNeuralNode(string name, Type type)

TypeInitializationException: The type initializer for 'Senparc.NeuChar.MessageHandlers.MessageHandler`3' threw an exception.
Senparc.NeuChar.MessageHandlers.MessageHandler<TC, TRequest, TResponse>..ctor(XDocument postDataDocument, int maxRecordCount, object postData)
```
```
ArgumentNullException: Value cannot be null.
 Parameter name: services
Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
Senparc.CO2NET.SenparcDI.GetIServiceProvider()
Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
Senparc.CO2NET.Cache.LocalObjectCacheStrategy+Nested..cctor()
```
```
TypeInitializationException: The type initializer for 'Nested' threw an exception.
Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
Senparc.NeuChar.Register.RegisterApiBind()
Senparc.NeuChar.Register..cctor()
```
完整的异常堆栈信息
```
An unhandled exception has occurred while executing the request. System.TypeInitializationException: The type initializer for 'Senparc.NeuChar.MessageHandlers.MessageHandler`3' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Senparc.NeuChar.Register' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: services
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetIServiceProvider()
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
   at Senparc.NeuChar.Register.RegisterApiBind()
   at Senparc.NeuChar.Register..cctor()
   --- End of inner exception stack trace ---
   at Senparc.NeuChar.Register.RegisterNeuralNode(String name, Type type)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3..cctor()
   --- End of inner exception stack trace ---
   at WeChat.Infrastructure.WeChatMessage.CustomMessageHandler.CustomMessageHandler..ctor(XDocument requestDocument, PostModel postModel, Int32 maxRecordCount) in E:\Project\WeChatMPProject\WeChat.Infrastructure\WeChatMessage\CustomMessageHandler\CustomMessageHandler.cs:line 29
   at WeChat.MPProject.Controllers.OpenAuthController.CallBack(String signature, String timestamp, String nonce, String msg_signature, String appId) in E:\Project\WeChatMPProject\WeChatMPProject\Controllers\API\OpenAuthController.cs:line 121
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```
![o17k4miu kaeku b y3x](https://user-images.githubusercontent.com/10153835/45729450-151bd400-bbff-11e8-8b49-3b4aa9a96e31.png)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：16.3.3
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：4.1.7
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by OrchesAdam** [comment]
@JeffreySu 
找到了
我没有在`Configure`里面注册`RegisterService` 这个服务
