### ISSUE TITLE
解密授权手机号数据偶尔会报Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by DekeYan** [JeffreySu/WeiXinMPSDK#1820]
##### 问题描述
用WxOpen.Helpers.EncryptHelper.DecodeEncryptedData解密数据获取用户授权手机号的时候，偶尔会出现错误，频率应该是百分之1的样子，具体错误信息
`System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
   at iReach.Lvyequan.Controllers.TokenAuthController.ExternalAuthenticateByAuthenticationPhone(ExternalAuthenticateByAuthenticationPhone model) in D:\Git\Lvyequan.Server\aspnet-core\src\iReach.Lvyequan.Web.Core\Controllers\TokenAuthController.cs:line 453
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
`

##### 重现问题步骤（如果可以）

1. 由小程序授权获取手机号，给服务器传入Code,EncryptedData和Iv
2. 服务器通过方法SnsApi.JsCode2JsonAsync 获取到当前的SessionKey
3.通过Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData解密数据获取到手机号，在这一步报错了

##### 发现问题的模块

- [x ] Senparc.Weixin.WxOpen 3.3.6：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
能不能记录一下所有的参数，对比一下每次这个1%是否有什么特殊的情况，比如这一次code为空了之类的。我们来找一下规律。

这个算法本身应该不会存在概率的问题。

**Comment by yorick520** [comment]
错误日志：

ExecptionMessage:Padding is invalid and cannot be removed.

mscorlib

   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)

   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)

   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()

   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)

   at System.IO.Stream.Close()

   at System.IO.Stream.Dispose()

   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)

   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)



加密数据：

sessionKey:98195476102492321891401391061935624977242；IV:116115241129461711788323441202601974169239；

encryptedData:deWfUALVVTxrux2cp0qeqLWotTHTIpRmIrpcuWoh3ngyr7vjCDYq1wh2Q0CE6Zj9P/V2ZVqtjkVAiGdBuBR8fSs9qpWhb9ieO5FoumuvgoM6HP5+7Eul6lm8njXJlbTZr+pODAIeMoBIwpQUPpCLwYtpSuKlQGKvsrmoVU5j5xgoKm4dyKmNwq3qcqE5Q+HUOV0r/c7GusFWZD0haaccduMjmKAyupCpbwdDu6kiVfEo1pVZdp5j4C5ihrZdE7gzeS9vOAFDaB+NXPB6Lz+H8js6BH8gVJ7tZ1KUAwqt+FIqHHBKsREKoyjePwREkRc1Sr/N+QR1vps2cFGpqp16NAoTyT/JFi2jNs8PgrrEYZkjVvyMUYFlDnq5BWNyyh5RX34JEq7EN62sc+wfAMB2Nrm/QEcBCtYLycP3xcQnCLasU2SQbpIr5GOUz7aiIu5rwMXMUDDg7jxCOA4+ORfSHUgS6OczRjY+QqrcfKmlA84=

**Comment by yorick520** [comment]
我的第一次授权不行，报错时候，在点一次可以，但是两次的数据一模一样

**Comment by yorick520** [comment]
问题二：：：： WeixinException
    AccessTokenOrAppId：
    Message：:Unable to cast object of type 'Senparc.Weixin.MP.Containers.OAuthAccessTokenBag' to type 'Senparc.Weixin.WxOpen.Containers.SessionBag'.
    StackTrace：
    InnerException：Unable to cast object of type 'Senparc.Weixin.MP.Containers.OAuthAccessTokenBag' to type 'Senparc.Weixin.WxOpen.Containers.SessionBag'.
    InnerException.StackTrace：   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Get[T](String key, Boolean isFullKey)
   at Senparc.Weixin.Containers.BaseContainer`1.TryGetItem(String shortKey)
   at Senparc.Weixin.WxOpen.Containers.SessionContainer.GetSession(String key)

**Comment by JeffreySu** [comment]
@yorick520  1 个 issue 建议只讨论 1 个问题，有其它问题可以另外开 Issue。

上一个问题里面，你说的两次数据一模一样是指传入到 `Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData` 方法里面的参数 100% 能确保是一样的吗？

**Comment by DekeYan** [comment]
> @yorick520 1 个 issue 建议只讨论 1 个问题，有其它问题可以另外开 Issue。
> 
> 上一个问题里面，你说的两次数据一模一样是指传入到 `Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData` 方法里面的参数 100% 能确保是一样的吗？
我的问题 和 @yorick520 描述是一样的，出现问题的时候第一次不成功第二次成功， DecodeEncryptedData 保证是没有变化的，只是SessionKey的值不确定有没有变化

**Comment by JeffreySu** [comment]
@DekeYan  我推测比较有可能的情况是sessionkey变化了，并且其中可能有一次为空

**Comment by yorick520** [comment]
如果是由于sessionkey变化了，如何解决？

**Comment by JeffreySu** [comment]
@yorick520  这个变化一般是因为sessionId变了，然后没有办法找到之前的seesionKey，所以，关键还是在监控sessionId是否有变化，这个你应该可以通过日志跟踪到的，可以验证一下这个猜测。

**Comment by JeffreySu** [comment]
@yorick520 有验证最后sessionId变化的情况吗？

**Comment by ChiakiYu** [comment]
引用一个解决方案
出自 [微信小程序加密解密 C# 以及 填充无效,无法被移除错误的解决方案 Padding is invalid and cannot be removed](https://www.cnblogs.com/microestc/p/11828654.html)
```
其次说一下为什么会第一次或间断性解密失败？

我开始的微信小程序代码 button 点击 -> 得到 iv,encryptedData -> wx.login -> 得到 code -> code,iv,encryptedData 发送服务器 -> 然后 code 得到 session_key  然后解密，

问题出在哪里呢，就出在点击 button 的地方，没有 wx.login 得到code 的时候，iv和encryptedData 就已存在一个session_key ,和之后得到的session_key 就不同了,

所以

在点击“获取信息”按钮 之前就应该先使用wx.login 得到code或者session_key，然后 点击 按钮 ，所以 在 onload 或者 onshow 里面 就应该 wx.login 得到 code或者 session_key
```

以及官网的建议：
[获取手机号](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)
```
注意
在回调中调用 wx.login 登录，可能会刷新登录态。此时服务器使用 code 换取的 sessionKey 不是加密时使用的 sessionKey，导致解密失败。建议开发者提前进行 login；或者在回调中先使用 checkSession 进行登录态检查，避免 login 刷新登录态。
```
