### ISSUE TITLE
小程序授权后获取用户信息：Padding is invalid and cannot be removed

### ISSUE THREAD

**Issue by ChiakiYu** [JeffreySu/WeiXinMPSDK#1869]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
开放平台已经关联了小程序，小程序授权后调用服务器端接口，该接口获取用户信息进行系统登录或注册。

经常出现以下错误，但是去主动重现的时候又不好重现：
 ```
 Padding is invalid and cannot be removed.
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
```

##### 重现问题步骤（如果可以）

代码：参考的官方demo
```
JsCode2JsonResult result;
 try
            {
                result = SnsApi.JsCode2Json(_wxOpenAppId, _wxOpenAppSecret, model.Code);
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException(ex.Message);
            }
//使用SessionContainer管理登录信息（推荐）
            var unionId = result.unionid;
            var sessionBag = SessionContainer.UpdateSession(null, result.openid, result.session_key, unionId);
            var sessionId = sessionBag.Key;

 var userInfo = EncryptHelper.DecodeUserInfoBySessionId(sessionId, model.EncryptedData, model.Iv);

```

##### 发现问题的模块

- [ ] Senparc.Weixin.WxOpen 版本

##### 模块对应的 .net 版本

- [x] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
你能获取到出错时候传入的参数吗？不然没法做测试，我这边用我们自己的账号线上的数据目前都是正常的。

**Comment by ChiakiYu** [comment]
这是参数：
```
{
        "code": "061XEgi416fgiT1eqDh4129di41XEgi8",
        "state": "Csproj_wxOpen_Bind",
        "returnUrl": "",
        "encryptedData": "h2l6AwWy/zXdBsBdG8S9Fxk9dzWuVPz7ubEZYOVIMBp6P4rRKvddMMqMIwAcctSCHaHujR+IOYcSXn60C0xZTppmWYDdtUh2vkaBjTXgMNoJKydgDpFPKH5cmDDIp7K4+wY3jjN+ffyEfWhf9aBXaZ6Ax+ksKV2+ugzpYKBAjRVUvvovHVTw8jmXX4En3OOoHsb86YHjQ2zRdxL+4zdhJ+OoENE0/3GePKrEjPwyIgGDPA7k1l5pgOvXIjcjTjT9PA7CcsW6pVCZWF5XvhI/i9t7bE3ccKXazIlnyufAyeE+HFlqhxsS+TAh+jETVfTmBIDE8q0f3pBoziqgLhDYZFtqKTHXbT+htpKMlR3RQxbgAymGwli0pHsKEk4WZgBXW5DzktuYXl4wMLq0YzEJrEcPcNc+UgK1j2oNr/qDltAsKXdIkiAFAgNKF3rhGLpKMBX/DYb06aDNYRMlIX9UdmUI4GGSGXyDTrs6OEWVik4A0LFPYt3yIAlUD6oCa0E650VBmM4x9gaYmD0ASoixWg==",
        "iv": "h94GfofE5mX8cYjpOpFFIQ==",
        "rawData": "{\"nickName\":\"嘿七\",\"gender\":1,\"language\":\"zh_CN\",\"city\":\"Qingdao\",\"province\":\"Shandong\",\"country\":\"China\",\"avatarUrl\":\"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83erRhP9rMOEABUhhWTeA0glB242r3Xxa4bLB8WdAhGVXicUmKaicyYYpCVY98yjQhdyR2PRQ8NicFNbUA/132\"}",
        "signature": "79e2d6e454d27f5a4eaf668cf7bba64d0fd887d0"
    }
```

这个异常，最近一个月出现了69次。
之前在调用`EncryptHelper.DecodeUserInfoBySessionId`之前，调用了
```
var checkSuccess = EncryptHelper.CheckSignature(sessionId, model.RawData, model.Signature);

                if (!checkSuccess)
                {
                    throw new UserFriendlyException("签名校验失败");
                }
```
会直接抛异常“签名校验失败”。
后来把这句取消了，直接调用

```
var userInfo = EncryptHelper.DecodeUserInfoBySessionId(sessionId, model.EncryptedData, model.Iv);
```
就出现了下方的异常
```
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
   at CsprojBuilder.Controllers.TokenAuthController.WxOpenAuthenticate(WxOpenOnLoginModel model) in D:\Work\Projects\Csproj.Jielong\aspnet-core\src\CsprojBuilder.Web.Core\Controllers\TokenAuthController.cs:line 483
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by JeffreySu** [comment]
@ChiakiYu sessionId 是多少？几个参数都要匹配

**Comment by ChiakiYu** [comment]
这个没记录  我打个log都记录一下 下次出问题我再更新

**Comment by JeffreySu** [comment]
OK

**Comment by ChiakiYu** [comment]
```
ERROR 2019-07-24 18:50:30,857 [180  ] TokenAuthController - ----------签名校验失败 开始-------------
ERROR 2019-07-24 18:50:30,859 [180  ] TokenAuthController - 提交的参数是：{"Code":"071GaTvK0UyoL92mO8yK0WlMvK0GaTvj","State":"Csproj_wxOpen_Bind","ReturnUrl":"","EncryptedData":"GiW4s+17o7RSaPOwGX8Ir1+3c/RYbHKvRzBg8UFlmIIiArLtU0ctkzjq1LRR5MH5CSPs63Jt4qCoFScSlRKlQ4/RVXXJFQV+r/1L+qKv/PdHRvVDLb+8P6CvPTurEuHsxlLyXTnnlEIu6IFYFzZWBMIp6+SHEK85mEb1gw4BtMmEy9EitnMskNjsEnmpI3M9r8ItKyQ8hinJejuno0JPXn3trc+2gMheNt4+4NwMTM6mzzGVO6g40NP7NjK9Tl6+An2TjBe+GGVFdrkl5hpYDXE/YO2FsL909faX3Y08msSuCVk5AsMGMJiUwddiu44KODdxCYfwLxBaIgYJEY6xLygFmAMuDg/L2g4/wDabBrhA5BNsD6lrcRRbvrHK65Lu3xd1oTXyMGbfUGTD4GLlLSJUX2FhcG7ZmHwg1jQUuKFHJu/AMQgdoPa/JONAu5Hjp0hL7ahr5LC0ghwdTfTowg3X1Ko9IgRxxj755eGgXQK7AnsMwjXzt4X+4YpOYpCb2LVSrTV2t4QjVNPe+Rjmsg==","Iv":"4y2ftkwAM2mF6Qc89HydpA==","RawData":"{\"nickName\":\"*Rebecca\",\"gender\":2,\"language\":\"zh_CN\",\"city\":\"Qingdao\",\"province\":\"Shandong\",\"country\":\"China\",\"avatarUrl\":\"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83epNuU1WTDS98s7OS06OmnNktDJyHkrjRmEJrDjheXnnETPOTtMcsMPP6q7Bn3TIorV28iaETTvl3sA/132\"}","Signature":"4a9a68b855b73f5a448d2b169a697ee14de5cf06"}
ERROR 2019-07-24 18:50:30,861 [180  ] TokenAuthController - SnsApi.JsCode2Json后的值是：{"openid":"o5mT-4xYKKfTYu4qjrZ6lpnZE7KY","session_key":"0sVkQ4CtcaiYJtvoPLBecw==","unionid":null,"errcode":0,"ErrorCodeValue":0,"errmsg":null,"P2PData":null}
ERROR 2019-07-24 18:50:30,866 [180  ] TokenAuthController - SessionContainer.UpdateSession后的值是：{"Key":"af597d2af90f4739a56563eadfcf6126","OpenId":"o5mT-4xYKKfTYu4qjrZ6lpnZE7KY","UnionId":null,"SessionKey":"0sVkQ4CtcaiYJtvoPLBecw==","ExpireTime":"2019-07-29T18:50:30.8572308+08:00","Name":null,"CacheTime":"2019-07-24T18:50:30.8572332+08:00"}
ERROR 2019-07-24 18:50:30,866 [180  ] TokenAuthController - ----------签名校验失败 结束-------------
ERROR 2019-07-24 18:50:30,890 [180  ] Mvc.ExceptionHandling.AbpExceptionFilter - Padding is invalid and cannot be removed.
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
   at CsprojBuilder.Controllers.TokenAuthController.WxOpenAuthenticate(WxOpenOnLoginModel model) in D:\aspnet-core\src\CsprojBuilder.Web.Core\Controllers\TokenAuthController.cs:line 486
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

对应代码：
```
            JsCode2JsonResult result;

            try
            {
                result = SnsApi.JsCode2Json(_wxOpenAppId, _wxOpenAppSecret, model.Code);
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException(ex.Message);
            }
            if (result.errcode != ReturnCode.请求成功)
            {
                throw new UserFriendlyException("错误：" + result.errmsg);
            }

            //使用SessionContainer管理登录信息（推荐）
            var unionId = result.unionid;
            var sessionBag = SessionContainer.UpdateSession(null, result.openid, result.session_key, unionId);
            var sessionId = sessionBag.Key;

            var checkSuccess = EncryptHelper.CheckSignature(sessionId, model.RawData, model.Signature);
            if (!checkSuccess)
            {
                //throw new UserFriendlyException("签名校验失败");
                Logger.Error("----------签名校验失败 开始-------------");
                Logger.Error("提交的参数是：" + JsonConvert.SerializeObject(model));
                Logger.Error("SnsApi.JsCode2Json后的值是：" + JsonConvert.SerializeObject(result));
                Logger.Error("SessionContainer.UpdateSession后的值是：" + JsonConvert.SerializeObject(sessionBag));
                Logger.Error("----------签名校验失败 结束-------------");
            }

            var userInfo = EncryptHelper.DecodeUserInfoBySessionId(sessionId, model.EncryptedData, model.Iv);
```

**Comment by JeffreySu** [comment]
我看了一下你的过程，如果 EncryptHelper.CheckSignature 没有通过，你强行进入到下一步，本身就有存在无法解密的情况，继续确定问题的话你需要回答几个问题：
1、是不是每次checkSuccess == false的时候（哪怕你强制继续），解密会失败？（有没有例外，例外的参数是怎么样的）
2、如果上一条有例外，请提供一条checkSuccess == false，并且解密成功情况下的传递到EncryptHelper.DecodeUserInfoBySessionId里面的参数（包括对应sessionBag里面的参数）

**Comment by JeffreySu** [comment]
例外你这一行是不是有问题：

```
var sessionBag = SessionContainer.UpdateSession(null, result.openid, result.session_key, unionId);
```

如果用户已经登录过了，第一个key不应该为null，应该是确定的sessionId吧，不然缓存会帮你分配另外一个sessionId（Key）。

**Comment by ChiakiYu** [comment]
> 我看了一下你的过程，如果 EncryptHelper.CheckSignature 没有通过，你强行进入到下一步，本身就有存在无法解密的情况，继续确定问题的话你需要回答几个问题：
> 1、是不是每次checkSuccess == false的时候（哪怕你强制继续），解密会失败？（有没有例外，例外的参数是怎么样的）
> 2、如果上一条有例外，请提供一条checkSuccess == false，并且解密成功情况下的传递到EncryptHelper.DecodeUserInfoBySessionId里面的参数（包括对应sessionBag里面的参数）


实际中，EncryptHelper.CheckSignature没有通过，直接抛异常的（就是我注释的那条）。
这次是为了展示异常信息。

**Comment by ChiakiYu** [comment]
> 例外你这一行是不是有问题：
> 
> ```
> var sessionBag = SessionContainer.UpdateSession(null, result.openid, result.session_key, unionId);
> ```
> 
> 如果用户已经登录过了，第一个key不应该为null，应该是确定的sessionId吧，不然缓存会帮你分配另外一个sessionId（Key）。

我试一下

**Comment by JeffreySu** [comment]
@ChiakiYu 新的 sessionBag 是可以的，我只是说这样不太到，会额外增加你很多冗余的数据，最终参加解密的是里面的 sessionKey。

另外，我做了几个不同的单元测试，发现一个奇怪的问题：微信加密的方式似乎并没有按照统一的标准，有些数据是可以的，有些就有问题，对于两种情况，需要分别启用或者禁用下面这行代码：

https://github.com/JeffreySu/WeiXinMPSDK/blob/56d5114880f72e727681f39dc8e41900e5646ca3/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Helpers/EncryptHelper.cs#L144

以下两个单元测试，分别在启用和禁用状态下，一个成功一个失败（第二个用的是你提供的数据）：

https://github.com/JeffreySu/WeiXinMPSDK/blob/56d5114880f72e727681f39dc8e41900e5646ca3/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen.Tests/Helpers/EncryptHelperTests.cs#L115

**Comment by ChiakiYu** [comment]
那请问。小程序授权获取用户信息正确的写法是什么呢？为啥只有我报错了。。。我是按照官方demo写的。。

**Comment by JeffreySu** [comment]
@ChiakiYu 不是只有你一个人碰到，感觉这个问题出现带有一定的随机性：

https://github.com/JeffreySu/WeiXinMPSDK/issues/1820

https://github.com/JeffreySu/WeiXinMPSDK/issues/1825

我会尝试提供一个容错处理的办法。

**Comment by JeffreySu** [comment]
@@ChiakiYu 我最后绕过一些padding的问题，强行解密出来了，是乱码，比较怀疑微信提供的或者上述提供的某些参数是有问题的。

**Comment by ChiakiYu** [comment]
引用一个解决方案
出自 [微信小程序加密解密 C# 以及 填充无效,无法被移除错误的解决方案 Padding is invalid and cannot be removed](https://www.cnblogs.com/microestc/p/11828654.html)
```
其次说一下为什么会第一次或间断性解密失败？

我开始的微信小程序代码 button 点击 -> 得到 iv,encryptedData -> wx.login -> 得到 code -> code,iv,encryptedData 发送服务器 -> 然后 code 得到 session_key  然后解密，

问题出在哪里呢，就出在点击 button 的地方，没有 wx.login 得到code 的时候，iv和encryptedData 就已存在一个session_key ,和之后得到的session_key 就不同了,

所以

在点击“获取信息”按钮 之前就应该先使用wx.login 得到code或者session_key，然后 点击 按钮 ，所以 在 onload 或者 onshow 里面 就应该 wx.login 得到 code或者 session_key
```

以及官网的建议：
[获取手机号](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)
```
注意
在回调中调用 wx.login 登录，可能会刷新登录态。此时服务器使用 code 换取的 sessionKey 不是加密时使用的 sessionKey，导致解密失败。建议开发者提前进行 login；或者在回调中先使用 checkSession 进行登录态检查，避免 login 刷新登录态。
```

**Comment by magisk317** [comment]
抱歉打扰各位，问个题外话，社区里有一个扫码取水设备，需要扫码登录
可能第一次我没点同意，或者误触了其他空白地方，导致没授权成功

结果，无论如何我都没办法重试了，只要我扫码，就报下边错，甚至我直接把域名发微信里点开，也是报同样的错，清理微信缓存，微信里清理缓存，均不行，怎么这辈子就吊死在这个歪脖子树上了么。。。。

求各位大佬支个招。。。域名: http://m.iot.jiuzhourunze.com/，原始域名带device id，扫完能直接定位到那台机器

![Screenshot_2024-06-07-00-08-24-257_com tencent mm](https://github.com/JeffreySu/WeiXinMPSDK/assets/93979778/c5152f13-91eb-4790-8982-ac8013623c03)
