### ISSUE TITLE
企业微信回调问题

### ISSUE THREAD

**Issue by fishjimi** [JeffreySu/WeiXinMPSDK#1936]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
完全参照Demo写的代码
创建WorkCustomMessageHandler时会爆炸.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Senparc.NeuChar.Context.GlobalMessageContext`3.GetMessageContext(TRequest requestMessage)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.GetCurrentMessageContext()
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.CommonInitialize(XDocument postDataDocument, Int32 maxRecordCount, IEncryptPostModel postModel)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3..ctor(Stream inputStream, IEncryptPostModel postModel, Int32 maxRecordCount)
   at Senparc.Weixin.Work.MessageHandlers.WorkMessageHandler`1..ctor(Stream inputStream, PostModel postModel, Int32 maxRecordCount)
```
PS：在3.0里面有不少兼容问题需要微调

##### 重现问题步骤（如果可以）

```
        [HttpPost]
        public async Task<ActionResult> ReceiveMessageAsync([FromQuery]PostModel postModel)
        {
            var maxRecordCount = 10;

            postModel.Token = _config.Token;
            postModel.EncodingAESKey = _config.EncodingAESKey;
            postModel.CorpId = _config.WeixinCorpId;

            //自定义MessageHandler，对微信请求的详细判断操作都在这里面。
            var stream = new MemoryStream();
            await Request.Body.CopyToAsync(stream);

            var messageHandler = new WorkCustomMessageHandler(_connection, stream, postModel, maxRecordCount);
            //执行微信处理过程
            messageHandler.Execute();
            //自动返回加密后结果
            return Content(messageHandler.TextResponseMessage);
        }
```

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] 其他模块：Senparc.NeuChar

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：269911478@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@fishjimi  今天凌晨已经发布了新版本，解决了相关的一个问题。因为上面没有写版本号，我无法确定您现在出错的版本，可以升级到最新的看一下。

**Comment by fishjimi** [comment]
@JeffreySu  我看到凌晨你解决的那个问题了
但是我用的是最新的版本，似乎是另一个问题
Senparc.Weixin.Work   （3.7.0）
Senparc.NeuChar   (1.0.100)

**Comment by JeffreySu** [comment]
@fishjimi 有没有请求的XML数据，我来测试一下。

**Comment by fishjimi** [comment]
@JeffreySu 对 是asp.net core 3.0 有劳了
`http://xxxxxxx?msg_signature=d2839fd884a18017f461511656c23d26fcce40f6&timestamp=1569355679&nonce=1569211517`
```
<xml>
    <ToUserName>
        <![CDATA[wwa92b2790089cd600]]>
    </ToUserName>
    <Encrypt>
        <![CDATA[533s+03v6J3n8kjpvI6ZYITi3OM9t0rOfY321Br6b1nMJOtDo7SCIAseINq/mzUmpp8MA6WLqiiZQx2I1z2+X+2AAGcjE0WCjKLH7lm0X1bnpjx3JF5sQlr3N8seSaPSa4pkee9A1LBdmgk6hJu4ErppE0xGXBDBnA7cJXSGM0Xh5hQ5T7/t53rsHyzCFv2qEsFV/hZk+zS8jwifh3UAAdOrD2AZhGLqKfl9jXcpyElKAB2xBuvCMpWQ431zPrhlW6jA3jV6C23jPtoB5a7Xlul5JX24IoILE9Klf57t11UXOGnll3DPEeLGuWM7M3zt/5qNVKemXeX6zgL6aOZiX5m9cEa3hf1T6ZcqGcUjgVnx032RaCrP6xCXiARZzd1JPKV0nEGugJ+4ImwE3kfrRk7y4MNvgzsLPtBTnHVP4iVl9mmuPUUpmR5lOFuEhpY6L6SFDJ+b1kanONCtrnW7LMihcCqbHoa3uacwGNWFw74JNV+lEWvURDleHveJYApiE66TEnHj29hRbHgGYommgkId4dtthKdDhkcEB6DlxfPJe+h6ZsqcS2jKoyj3Rj18QCKN1rJB4NBC9NqFPduZgycR/2KdDyvJ0hAEWhRWFneeNsDeYz/MANExzVhn3pLjaP4MLuu49GOoSnUBJLUX1SSw5YhQnO8yGKKtGTA5JjoOe8Hwm3E2QcdOJ583p/zwczNkDgUHGy2wV87P9IOBcUtRV+pO0NxZKLfaV7yCpJvgZztsfWgKMheEJNPiFB7O41aVB+tqo/ROU0GL+0Ti++A4Wtn9k7QYQ6yh9mBn6pcxp+eY52ZgOqi2/ncj092MmsxyX8CXddTsxX/NZw4X0A==]]>
    </Encrypt>
    <AgentID>
        <![CDATA[]]>
    </AgentID>
</xml>
```

**Comment by JeffreySu** [comment]
是否方便提供一下解密的参数：zsu@senparc.com

**Comment by fishjimi** [comment]
@JeffreySu 邮件已发送

**Comment by JeffreySu** [comment]
@JeffreySu 试一下最新的 Work v3.7.0.1，应该已经解决了，之前确实处理有问题，有一个地方没有赋值。

**Comment by fishjimi** [comment]
@JeffreySu 好的，多谢！
PS：你@了你自己

**Comment by JeffreySu** [comment]
🤣
