### ISSUE TITLE
.net core 升级到3.0  Senparc升级到9月25日的最新版本  启动后报错

### ISSUE THREAD

**Issue by wshuai222333** [JeffreySu/WeiXinMPSDK#1939]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
.net core 升级到3.0  Senparc升级到9月25日的最新版本  启动后报错
>dotnet run
RegisterApiBind Time: 254.18560000000002ms, Api Count:1208, Error Count: 0
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.RegisterAsync(String appId, String appSecret, String name)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.Register(String appId, String appSecret, String name)
   at Senparc.Weixin.MP.Register.RegisterMpAccount(IRegisterService registerService, String appId, String appSecret, String name)
   at Senparc.Weixin.MP.Register.RegisterMpAccount(IRegisterService registerService, ISenparcWeixinSettingForMP weixinSettingForMP, String name)
   at Travel.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider svp, IOptions`1 senparcSetting, IOptions`1 senparcWeixinSetting) in C:\mycode\Travel.Api\Travel.Api\Startup.cs:line 220
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.RegisterAsync(String appId, String appSecret, String name)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.Register(String appId, String appSecret, String name)
   at Senparc.Weixin.MP.Register.RegisterMpAccount(IRegisterService registerService, String appId, String appSecret, String name)
   at Senparc.Weixin.MP.Register.RegisterMpAccount(IRegisterService registerService, ISenparcWeixinSettingForMP weixinSettingForMP, String name)
   at Travel.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider svp, IOptions`1 senparcSetting, IOptions`1 senparcWeixinSetting) in C:\mycode\Travel.Api\Travel.Api\Startup.cs:line 220
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Travel.Api.Program.Main(String[] args) in C:\mycode\Travel.Api\Travel.Api\Program.cs:line 11

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ 4.7.0] Senparc.Weixin.Open 版本：
- [ 1.5.0 ] Senparc.Weixin.TenPay 版本：
- [ 3.7.0 ] Senparc.Weixin.Work 版本：
- [ 3.7.0] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x
- [x] .net core 3.x
##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：wangshuai@reapal.com

**Comment by JeffreySu** [comment]
@wshuai222333 这个错误看上去你提交的 appId 参数是 null，可以跟踪检查一下。

**Comment by JeffreySu** [comment]
比如你的 appsettings.json 配置是否正确？

**Comment by wshuai222333** [comment]
是 配置文件的问题  谢谢
