### ISSUE TITLE
MP 调用OAuthApi.GetAccessTokenAsync，不能创建Socket连接

### ISSUE THREAD

**Issue by lvbin-jk** [JeffreySu/WeiXinMPSDK#2016]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

按照官网的 CO2NET Demo：https://github.com/Senparc/Senparc.CO2NET/blob/master/Sample/Senparc.CO2NET.Sample.netcore/Startup.cs配置的；环境Centos7+docker+dotnet core2.2,其他发起Http请求的地方都正常，而且我们也是用的HttpClientFactory;除了调用GetAccessTokenAsync方法，还尝试之间用Senparc.CO2NET.HttpGetAsync方法访问百度也是同样的错误，Senparc.CO2NET.HttpGetAsync在创建HttpClient的时候名称是默认的还是需要在配置文件给呢?

##### 重现问题步骤（如果可以）

ERROR 2019-10-29 10:42:58,620 [33   ] Mvc.ExceptionHandling.AbpExceptionFilter - Resource temporarily unavailable
System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  at System.Threading.Tasks.ValueTask`1.get_Result()
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Threading.Tasks.ValueTask`1.get_Result()
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
  at System.Threading.Tasks.ValueTask`1.get_Result()
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
  at Senparc.CO2NET.HttpUtility.RequestUtility.HttpGetAsync(String url, Encoding encoding)
  at Senparc.CO2NET.HttpUtility.Get.GetJsonAsync[T](String url, Encoding encoding, Action`2 afterReturnText)
  at Senparc.Weixin.MP.CommonAPIs.CommonApi.GetTokenAsync(String appid, String secret, String grant_type)
  at Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenResultAsync(String appId, Boolean getNewToken)
  at Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenAsync(String appId, Boolean getNewToken)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x ] .net core 2.x
- [] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
除了GetAccessTokenAsync，调用其他接口也一样有问题吗？
