### ISSUE TITLE
AccessTokenContainer.RegisterAsync并发环境下报错

### ISSUE THREAD

**Issue by Caskia** [JeffreySu/WeiXinMPSDK#2070]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
AccessTokenContainer.RegisterAsync在多线程情况下报错，因为我的项目需要动态注册多个商户的APPID，所以程序会在多线程场景下进行注册绑定。查看源码原因在```RegisterFuncCollection```并未使用并发字典```ConcurrentDictionary```。是否可以支持并发注册？
```
System.TypeInitializationException: The type initializer for 'Nested' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'services')
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
   at Senparc.CO2NET.SenparcDI.GetIServiceProvider(Boolean useGlobalScope)
   at Senparc.CO2NET.SenparcDI.GetService[T](Boolean useGlobalScope)
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.get_Instance()
   at Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
   at Senparc.CO2NET.Cache.CacheStrategyFactory.GetExtensionCacheStrategyInstance(ICacheStrategyDomain cacheStrategyDomain)
   at Senparc.Weixin.Cache.ContainerCacheStrategyFactory.GetContainerCacheStrategyInstance()
   at Senparc.Weixin.Containers.BaseContainer`1.get_Cache()
   at Senparc.Weixin.Containers.BaseContainer`1.CheckRegisteredAsync(String shortKey)
```

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [] Windows，版本：
- [x] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

**Comment by JeffreySu** [comment]
@Caskia 升级到最新的版本还有这个问题吗？

**Comment by Caskia** [comment]
我已经修改了代码逻辑，做了一个队列进行单线程操作。你是在新版中修改了这个问题吗？

**Comment by JeffreySu** [comment]
@Caskia 一方面是已经使用了ConcurrentDictionary，另外一方面有相关涉及的底层代码也有优化（虽然不是专为这个问题）。
