### ISSUE TITLE
System.Net.Sockets.SocketException: 由于线程退出或应用程序请求，已中止 I/O 操作

### ISSUE THREAD

**Issue by Winches** [JeffreySu/WeiXinMPSDK#2079]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
使用企业微信SDK发送消息，接口为Senparc.Weixin.Work.AdvancedAPIs.MassApi.SendText，
服务器为Windows Server2012R2，SDK Version为3.7.0.1。
错误信息如下：

System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。. ---> System.Net.Sockets.SocketException: 由于线程退出或应用程序请求，已中止 I/O 操作。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.CO2NET.HttpUtility.Post.PostGetJson[T](String url, CookieContainer cookieContainer, Stream fileStream, Encoding encoding, String certName, Boolean useAjax, Boolean checkValidationResult, Action`2 afterReturnText, Int32 timeOut)
   at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting)
   at Senparc.Weixin.Work.AdvancedAPIs.MassApi.<>c__DisplayClass2_0.<SendText>b__0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.Work.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppKey, Boolean retryIfFaild)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x
- [ ] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
先查一下网络问题，换一个网络环境看看。

**Comment by Winches** [comment]
> 先查一下网络问题，换一个网络环境看看。

大概率是网络问题吗？可惜的是我这边没有网络的控制权。

**Comment by JeffreySu** [comment]
对。

**Comment by wtujvk** [comment]
组件默认的请求超时时间设置多少秒 ？
我这边也遇到这个问题了，搭建了一个本地测试接口环境。
然后设置 Senparc.Weixin.Config.ApiMpHost = "http://localhost:5000";  Senparc.Weixin.Config.ApiMpFileHost = "http://localhost:5000";
在上传永久素材的时候偶尔会出现这个问题。服务端有接收到文件并且没发现报错的情况。

客户端日志：
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(IServiceProvider serviceProvider, String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(IServiceProvider serviceProvider, String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.CO2NET.HttpUtility.Post.PostFileGetJson[T](IServiceProvider serviceProvider, String url, CookieContainer cookieContainer, Dictionary`2 fileDictionary, Dictionary`2 postDataDictionary, Encoding encoding, String certName, Boolean useAjax, Action`2 afterReturnText, Int32 timeOut)
   at Senparc.Weixin.MP.AdvancedAPIs.MediaApi.<>c__DisplayClass6_0.<UploadForeverMedia>b__0(String accessToken)


服务端部分代码
![image](https://user-images.githubusercontent.com/17868266/210306058-48844ff4-4504-42d1-af76-fb8a50049a68.png)
![image](https://user-images.githubusercontent.com/17868266/210305970-bb1fcb44-3c3d-41a8-bad7-6228737ee07a.png)

**Comment by wtujvk** [comment]
查看了下，接口默认时间是10秒。可以尝试把超时时间调大些。
`MediaApi.UploadForeverMedia(accessTokenOrAppId, physicFilePath, UploadForeverMediaType.image)`
改为
`MediaApi.UploadForeverMedia(accessTokenOrAppId, physicFilePath, UploadForeverMediaType.image, 30 * 1000)`
修改后暂时没有出现The operation was canceled. 了。

图片素材大小限制是10M, 所以可能会有大文件，超时时间设置为10秒不一定够。
[新增永久素材](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html)
