### ISSUE TITLE
master分支运行后，消息模拟器 报错

### ISSUE THREAD

**Issue by ChiakiYu** [JeffreySu/WeiXinMPSDK#2228]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

git克隆master分支后，直接运行Samples\netcore3.0-mvc，然后消息模拟器发送文本，报错

##### 重现问题步骤（如果可以）

1. git克隆master分支
2. 用vs2019运行Samples\netcore3.0-mvc
3.关闭ssl，运行，找到工具箱-消息模拟器，填写好URL、Token、类型：文本、Content、取消选中“测试并发性能”后提交，报错

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Senparc.NeuChar
  StackTrace:
   at Senparc.NeuChar.Agents.MessageAgent.RequestXml(IMessageHandlerBase messageHandler, String url, String token, Stream stream, Boolean autoFillUrlParameters, Boolean useNeuCharKey, Int32 timeOut)
   at Senparc.NeuChar.Agents.MessageAgent.RequestXml(IMessageHandlerBase messageHandler, String url, String token, String xml, Boolean autoFillUrlParameters, Int32 timeOut)
   at Senparc.Weixin.Sample.NetCore3.Controllers.SimulateToolController.Index(String url, String token, RequestMsgType requestType, Nullable`1 eventType, Boolean testConcurrence, Int32 testConcurrenceCount, Boolean testEncrypt, String encodingAESKey, String appId) in E:\Work\Study\WeiXinMPSDK\Samples\netcore3.0-mvc\Senparc.Weixin.Sample.NetCore3\Controllers\Tools\SimulateToolController.cs:line 412

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：master
- [ ] Senparc.Weixin.MP 版本：master
- [ ] Senparc.Weixin.MP.MVC 版本：master
- [ ] Senparc.Weixin.Open 版本：master
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：master
- [ ] Senparc.Weixin.WxOpen 版本：master
- [ ] Senparc.Weixin.Cache.Redis 版本：master
- [ ] Senparc.Weixin.Cache.Memcached 版本：master
- [ ] 其他模块：master

##### 模块对应的 .net 版本

- [x] .net core 3.1

##### 开发环境

- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 系统环境

- [x] Windows，版本：win10

**Comment by JeffreySu** [comment]
@ChiakiYu 确实有错误。

**Comment by JeffreySu** [comment]
@ChiakiYu 已经修复代理转发消息的相关bug，非常感谢！

**Comment by ChiakiYu** [comment]
好使了
感谢修复
感谢
