### ISSUE TITLE
微信信息推送时一个很奇怪的问题

### ISSUE THREAD

**Issue by yueliuhun** [JeffreySu/WeiXinMPSDK#2352]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
描述：错误异常
错误信息：Unexpected end of request content.
堆栈信息：   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelBadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at Senparc.CO2NET.AspNet.HttpUtility.RequestUtility.GetRequestMemoryStream(HttpRequest request)
   at ABC.Controllers.WeiXinController.Index(PostModel postModel) in D:\备份\ABCLinux\ABC\ABC\Controllers\WeiXinController.cs:line 365
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

===================以下是代码===============

  public async Task<IActionResult> Index(PostModel postModel)
        {
           

            if (!CheckSignature.Check(postModel.Signature, postModel.Timestamp, postModel.Nonce, Token))
            {
                return Content("参数错误！");
            }

            #region 打包 PostModel 信息

            postModel.Token = Token;//根据自己后台的设置保持一致
            postModel.EncodingAESKey = EncodingAESKey;//根据自己后台的设置保持一致
            postModel.AppId = AppId;//根据自己后台的设置保持一致（必须提供）

            #endregion
            var cancellationToken = new CancellationToken();//给异步方法使用
            //v4.2.2之后的版本，可以设置每个人上下文消息储存的最大数量，防止内存占用过多，如果该参数小于等于0，则不限制（实际最大限制 99999）
            //注意：如果使用分布式缓存，不建议此值设置过大，如果需要储存历史信息，请使用数据库储存
            var maxRecordCount = 90;

            //自定义MessageHandler，对微信请求的详细判断操作都在这里面。
            var messageHandler = new CustomMessageHandler(Request.GetRequestMemoryStream(), postModel, maxRecordCount);

            #region 设置消息去重设置

            /* 如果需要添加消息去重功能，只需打开OmitRepeatedMessage功能，SDK会自动处理。
             * 收到重复消息通常是因为微信服务器没有及时收到响应，会持续发送2-5条不等的相同内容的 RequestMessage */
            messageHandler.OmitRepeatedMessage = true;//默认已经是开启状态，此处仅作为演示，也可以设置为 false 在本次请求中停用此功能

            #endregion

            try
            {
                messageHandler.SaveRequestMessageLog();//记录 Request 日志（可选）
                await messageHandler.ExecuteAsync(cancellationToken);//执行微信处理过程（关键）

                //messageHandler.SaveResponseMessageLog();//记录 Response 日志（可选）
                //return Content(messageHandler.ResponseDocument.ToString());//v0.7-
                return new WeixinResult(messageHandler);//v0.8+
                //return new FixWeixinBugWeixinResult(messageHandler);//为了解决官方微信5.0软件换行bug暂时添加的方法，平时用下面一个方法即可
            }
            catch (Exception ex)
            {
                #region 异常处理
                WeixinTrace.Log("MessageHandler错误：{0}", ex.Message);

                using (TextWriter tw = new StreamWriter(ServerUtility.ContentRootMapPath("~/App_Data/Error_" + _getRandomFileName() + ".txt")))
                {
                    tw.WriteLine("ExecptionMessage:" + ex.Message);
                    tw.WriteLine(ex.Source);
                    tw.WriteLine(ex.StackTrace);
                    //tw.WriteLine("InnerExecptionMessage:" + ex.InnerException.Message);

                    if (messageHandler.ResponseDocument != null)
                    {
                        tw.WriteLine(messageHandler.ResponseDocument.ToString());
                    }

                    if (ex.InnerException != null)
                    {
                        tw.WriteLine("========= InnerException =========");
                        tw.WriteLine(ex.InnerException.Message);
                        tw.WriteLine(ex.InnerException.Source);
                        tw.WriteLine(ex.InnerException.StackTrace);
                    }

                    tw.Flush();
                    tw.Close();
                }
                return Content("");
                #endregion
            }
        }`

####个人疑问
我怀疑是因为异步cancellationToken引起的，请求时中断导致！
但是微信向这里发送信息，什么情况才会中断？想不通，也没办验证

##### 重现问题步骤（如果可以）
不能，偶尔出现，原因未知
平均一天出现10次左右！

##### 发现问题的模块

- [x] Senparc.Weixin 版本：6.8.400
- [x] Senparc.Weixin.MP 版本：16.11.400
- [x] Senparc.Weixin.MP.MVC 版本：7.6.400
- [x] Senparc.Weixin.WxOpen 版本：3.10.400
- [x] Senparc.CONET 版本：1.3.300
- [ ]  Senparc.CONET.APM 版本：0.9.300
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [x] .net core 5.0.5

##### 开发环境

- [x] Visual Studio 2019

- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 系统环境

- [x] Linux，版本：CentOS 7.9.2009
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：liuhun@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
看一下服务器的设置是否有问题？例如.NET Core或者Linux上面建议打开同步的设置AllowSynchronousIO

**Comment by yueliuhun** [comment]
在LINUX下一直是开着的
services.Configure<KestrelServerOptions>(options => options.AllowSynchronousIO = true);
一直分析不到原因
这个问题主要就是发生在微信向我接口推送消息时
Kestrel的配置我也放到最大了，我一直以为是Kestrel处理不了
"MaxConcurrentConnections": null,
"MaxConcurrentUpgradedConnections": null

盛派记录的日志，就是有LOG的事件与记录，一天差不多是7W条！我觉得这个量不高啊！扫码、关注，发送模板消息，用户发送消息，这些都包含在内的。
服务器的资源我也检查，CPU,内存，硬盘IO，全没问题（资源占用非常低，峰值不超过20%）一般都晨2%左右，硬盘IOPS/15
我想确认下是哪个环节，或什么情况，产生这样的问题，一天就几次！

我抓下数据，发生问题时，上下文请求的报文，再贴看看

netcore是直接使用 Nginx 1.19.8 反向代理映射到 http://localhost:5050

**Comment by JeffreySu** [comment]
你有没有什么防火墙（软件/硬件）之类的，会去拦截掉一些请求？看错误信息是没有得到完整的信息（Request）结尾。

**Comment by yueliuhun** [comment]
没有软防硬防，就是标准的华为云默认设置，开放必要的端口
从上面的提示，肯定是Request没有完整的内容，但是这个内容是由微信推送到我的消息接收接口！可能是网络间歇性的故障？
我准备换个网络，把整个事件发生时请求来源记录下，看看具体是什么原因。从Nginx日志到响应日志，再看看！
发在这是让大家帮我分析下原因。
脑壳疼。。

**Comment by JeffreySu** [comment]
如果你确定软件层面配置和防火墙没问题，一般是网络问题，包括DNS问题。

**Comment by yueliuhun** [comment]
这个问题最终解决了，是网络问题，用的是华为云。能过抓包发现，在发包的时候会一直重试，并且只发一部份，具体什么原因 也不知道，没时间解决，最后是换了一台服务器就正常了

**Comment by zouzjidelu** [comment]
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelBadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at Senparc.CO2NET.AspNet.HttpUtility.RequestUtility.GetRequestMemoryStream(HttpRequest request)
   at XDApi.Controllers.WeChatController.Handler(PostModel postModel) in G:\code\dotnetcore\trunck\XD.Core\XDApi\Controllers\Wechats\Events\WeChatController.cs:line 121


@yueliuhun @JeffreySu  我也遇到了同样问题。，今天在公众号发了一次推文，流量1个小时内  uv 1.5w左右 pv 10w左右。出现了此问题。我们的网络带宽50M。从云服务器上看网络带宽是没有超的。会不会不是网络问题呢？麻烦给解答下。是用户点击公众号菜单 ，推送事件 访问我们服务器得到的错误消息。我们的服务器是windows server

**Comment by yueliuhun** [comment]
我当时就是换网络了就正常了，就是网络问题 @zouzjidelu
