### ISSUE TITLE
tenpayV3 退款失败

### ISSUE THREAD

**Issue by dodu2014** [JeffreySu/WeiXinMPSDK#2496]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
v3退款失败~~

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [x] Senparc.Weixin.TenpayV3 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：dodu@live.cn

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by dodu2014** [comment]
本地正常, 在服务器端提示: 系统找不到指定的文件。

异常信息:
[[[BaseException]]]
[2021/11/01 17:59:11.0531]
[线程：48]
	BaseException
	Message：系统找不到指定的文件。
	StackTrace：
	InnerException：系统找不到指定的文件。
	InnerException.StackTrace：   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Senparc.Weixin.TenPayV3.Helpers.TenPaySignHelper.CreateSign(String message, String privateKey)
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.BuildAuthAsync(HttpRequestMessage request)
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.GetHttpResponseMessageAsync(String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkDataNotNull)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.RequestAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func`1 createDefaultInstance)

不知道你们遇见这种情况没有?

**Comment by JeffreySu** [comment]
@dodu2014 没有碰到这样的情况，如果有更详细的信息可以提供一下。或者也建议升级到最新的版本试一下。
