### ISSUE TITLE
tenpayV3 线上版本退款失败 tenpayV3 线上版本退款失败

### ISSUE THREAD

**Issue by dodu2014** [JeffreySu/WeiXinMPSDK#2521]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

**退款失败, 提示未能找到指定文件**.

异常追踪:
[[[BaseException]]]
[2021/11/29 18:14:10.0807]
[线程：48]
BaseException
Message：系统找不到指定的文件。
StackTrace：
InnerException：系统找不到指定的文件。
InnerException.StackTrace： at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan1 keyBlob, Boolean encrypted, ReadOnlySpan1 password)
at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan1 keyBlob) at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan1 source, Int32& bytesRead)
at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan1 source, Int32& bytesRead) at Senparc.Weixin.TenPayV3.Helpers.TenPaySignHelper.CreateSign(String message, String privateKey) at Senparc.Weixin.TenPayV3.TenPayHttpHandler.BuildAuthAsync(HttpRequestMessage request) at Senparc.Weixin.TenPayV3.TenPayHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) at Senparc.Weixin.TenPayV3.TenPayApiRequest.GetHttpResponseMessageAsync(String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkDataNotNull) at Senparc.Weixin.TenPayV3.TenPayApiRequest.RequestAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func1 createDefaultInstance)

而**在开发环境中是正常的**, 可以**正确发起退款**.

@JeffreySu @JeffreySu @JeffreySu 

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] Visual Studio 2019
- [x] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：windows server 2016
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：dodu@live.cn

**Comment by dodu2014** [comment]
debug模式发布, 或 发布为独立模式, 都提示: 系统找不到指定的文件

而在开发环境中, 正常发起退款...

官方能否协助处理检查一下问题所在 这个问题已经过不去了.... 🤣

以下是退款日志:

[[[接口调用]]]
[2021/11/29 20:51:46.4758]
[线程：18]
	URL：https://api.mch.weixin.qq.com/v3/refund/domestic/refunds
	Post Data：
{"transaction_id":"4200001302202111299022415928","out_trade_no":"211129205110935-9958-8320","out_refund_no":"no-637738159064595987","reason":"退款申请","notify_url":"https://www.fengyoutang.com/mall/Orders/refundNotify","amount":{"refund":1,"total":1,"currency":"CNY"}}

[[[BaseException]]]
[2021/11/29 20:51:46.4838]
[线程：18]
	BaseException
	Message：系统找不到指定的文件。
	StackTrace：
	InnerException：系统找不到指定的文件。
	InnerException.StackTrace：   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Senparc.Weixin.TenPayV3.Helpers.TenPaySignHelper.CreateSign(String message, String privateKey)
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.BuildAuthAsync(HttpRequestMessage request)
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.GetHttpResponseMessageAsync(String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkDataNotNull)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.RequestAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func`1 createDefaultInstance)

**Comment by JeffreySu** [comment]
1、看一下服务器对证书文件的访问权限（以及包括是否存在和正确）；
2、确认无误后，建议你先部署一下我们官方的 Sample（除了 appsettings.json 别的都不需要修改），是可以正常退款的：https://sdk.weixin.senparc.com/TenPayRealV3/ProductList，然后对比一下哪里的代码有问题。

**Comment by dodu2014** [comment]
@JeffreySu 感谢你抽出时间答复 issues, 可现在还是遇到了这样的问题. 
这是我换的其他公众号和对应支付商户号, 证书新安装的, 确保证书存在, 路径也是正确的(配置的绝对路径)

下载了官方最新版的sample, 按你的要求, 除了改了appsettings.json中的相关的微信配置, 和 TenPayRealV3Controller 控制器中生成qrcode 的域名, 其他什么都没动.

appsettings.json 配置如下
![image](https://user-images.githubusercontent.com/15245544/144115628-9b938a58-96af-446d-ba68-b6e996de53ee.png)

然后跑起来的时候是这样的:
![image](https://user-images.githubusercontent.com/15245544/144114879-29156464-b72d-4704-9cf3-c2f4a0501943.png)

查看日志如下, 还是这样的问题:

[[[接口调用]]]
[2021/12/01 03:25:31.7951]
[线程：56]
	URL：https://api.mch.weixin.qq.com/v3/pay/transactions/native
	Post Data：
{"appid":"wx9ca813c9159806ac","mchid":"1602015574","description":"产品1 - 微信支付 V3 - Native 支付","out_trade_no":"160201557420211201032531433528","time_expire":"2021-12-01T04:25:31.795+08:00","notify_url":"http://test.5shiguang.net/TenpayRealV3/PayNotifyUrl","amount":{"total":1,"currency":"CNY"}}

[[[BaseException]]]
[2021/12/01 03:25:31.7956]
[线程：56]
	BaseException
	Message：系统找不到指定的文件。
	StackTrace：
	InnerException：系统找不到指定的文件。
	InnerException.StackTrace：   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Senparc.Weixin.TenPayV3.Helpers.TenPaySignHelper.CreateSign(String message, String privateKey) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\Helpers\TenPaySignHelper.cs:line 79
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.BuildAuthAsync(HttpRequestMessage request) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayHttpHandler.cs:line 114
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayHttpHandler.cs:line 88
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.GetHttpResponseMessageAsync(String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkDataNotNull) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayApiRequest.cs:line 147
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.RequestAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func`1 createDefaultInstance) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayApiRequest.cs:line 181

[[[BaseException]]]
[2021/12/01 03:25:31.7961]
[线程：56]
	BaseException
	Message：系统找不到指定的文件。
	StackTrace：
	InnerException：系统找不到指定的文件。
	InnerException.StackTrace：   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Senparc.Weixin.TenPayV3.Helpers.TenPaySignHelper.CreateSign(String message, String privateKey) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\Helpers\TenPaySignHelper.cs:line 79
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.BuildAuthAsync(HttpRequestMessage request) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayHttpHandler.cs:line 114
   at Senparc.Weixin.TenPayV3.TenPayHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayHttpHandler.cs:line 88
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.GetHttpResponseMessageAsync(String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkDataNotNull) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayApiRequest.cs:line 147
   at Senparc.Weixin.TenPayV3.TenPayApiRequest.RequestAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func`1 createDefaultInstance) in E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayApiRequest.cs:line 181

**Comment by dodu2014** [comment]
@JeffreySu @JeffreySu @JeffreySu

**Comment by JeffreySu** [comment]
你确定用的是最新的V3支付吗？最新的V3是不需要装证书的。

**Comment by dodu2014** [comment]
是的, 你看上面日志, 提示的错误行的文件. @JeffreySu 

E:\Gitee\WeiXinMPSDK\src\Senparc.Weixin.TenPay\Senparc.Weixin.TenPayV3\HttpHandlers\TenPayApiRequest.cs:line 181

<img width="329" alt="image" src="https://user-images.githubusercontent.com/15245544/144438023-a5ad11f5-a3a0-4050-9a15-a339e53c2f58.png">

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/15245544/144438134-b6321de7-04cc-48f4-b9b6-d591b5a5c961.png">

**Comment by JeffreySu** [comment]
TenPayV3 的验证方式已经不需要证书了，你跟踪看一下 CreateSign() 这个方法里面，传入参数，以及每个过程里面的数据，和你本地运行的是否一致？
