### ISSUE TITLE
Message：RequestMessage转换出错！可能是MsgType和InfoType都不存在！

### ISSUE THREAD

**Issue by xxgg945** [JeffreySu/WeiXinMPSDK#2599]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

2022-03-17 16:47:02.714 +08:00 [INF] Message：RequestMessage转换出错！可能是MsgType和InfoType都不存在！，XML：<xml>
  <SuiteId><![CDATA[ww97f0b3722183df55]]></SuiteId>
  <AuthCorpId><![CDATA[wpppCKCAAAegM9ELhw9B2yWsNdfSWPTg]]></AuthCorpId>
  <InfoType><![CDATA[change_external_chat]]></InfoType>
  <TimeStamp>1647506822</TimeStamp>
  <ChatId><![CDATA[wrppCKCAAA_Nr5sHo4tA6UOitS4TPlCg]]></ChatId>
  <ChangeType><![CDATA[update]]></ChangeType>
  <UpdateDetail><![CDATA[del_member]]></UpdateDetail>
  <QuitScene>0</QuitScene>
  <MemChangeCnt>1</MemChangeCnt>
</xml>StackTrace：   at Senparc.Weixin.Work.RequestMessageFactory.GetRequestEntity[TMC](TMC messageContext, XDocument doc)
   at Senparc.Weixin.Work.MessageHandlers.WorkMessageHandler`1.Init(XDocument postDataDocument, IEncryptPostModel postModel)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.CommonInitialize(XDocument postDataDocument, Int32 maxRecordCount, IEncryptPostModel postModel, Boolean onlyAllowEncryptMessage, IServiceProvider serviceProvider)
   at WxOpen.Web.Controllers.WorkController.callback(PostModel postModel, CancellationToken cancellation) in /data/jenkins/workspace/live-weixin/WxOpen.Web/Controllers/WorkController.cs:line 109
##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [] Windows，版本：
- [x ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JaneConan** [comment]
@xxgg945 您好，请问一下您这个issue和 #2932 是不是一样的
请看一下 回复，谢谢

我们看到在 v3.18.1版本 已经修复了您的这个问题，请问您，目前又再次测试过么，谢谢
https://github.com/JeffreySu/WeiXinMPSDK/issues/2932
