### ISSUE TITLE
The SSL connection could not be established, see inner exception (Windows)

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#2719]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
 #2207 问题类似，但是环境不一样。

##### 重现问题步骤（如果可以）

1. 接入公众号报错
调用方法 SenparcAccessTokenContainer.TryGetAccessToken
另外http://www.yshizi.cn/178.html 这个地址404了

##### 微信官方文档快照（直接复制关键内容到下方）

异常详细信息：

异常堆栈：   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpGetAsync(IServiceProvider serviceProvider, String url, Encoding encoding)
   at Senparc.CO2NET.HttpUtility.Get.GetJsonAsync[T](IServiceProvider serviceProvider, String url, Encoding encoding, Action`2 afterReturnText)
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.GetTokenAsync(String appid, String secret, String grant_type)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenResultAsync(String appId, Boolean getNewToken)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenAsync(String appId, Boolean getNewToken)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.TryGetAccessTokenAsync(String appId, String appSecret, Boolean getNewToken)
   at PowerEasy.Modules.Weixin.Admin.Business.SenparcAccessTokenContainer.TryGetAccessToken(String appId, String appSecret, Boolean getNewToken)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：16.7.8
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x
- [ ] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：Windows Server 2016 Standard
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by wtujvk** [comment]
还是能重现问题， 可能是配置问题 ？ （同一份代码不同环境下有的电脑可以，有的不行）
Senparc.Weixin.MP 版本：16.18.5.10 
net 6.0
Windows Server 2016 Standard

**Comment by wtujvk** [comment]
最后发现是网络问题
