### ISSUE TITLE
Senparc.Weixin.TenPayV3 jsapi下单接口 系统找不到指定文件

### ISSUE THREAD

**Issue by ntzw** [JeffreySu/WeiXinMPSDK#2744]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
```
var basePayApis2 = new Senparc.Weixin.TenPayV3.TenPayHttpClient.BasePayApis2(_httpClient, _tenpayV3Setting);
var result = await basePayApis2.JsApiAsync(jsApiRequestData);
```

[[[BaseException]]]
[2022/12/16 02:12:33.9498]
[线程：10]
	BaseException
	Message：系统找不到指定的文件。
	StackTrace：
	InnerException：系统找不到指定的文件。
	InnerException.StackTrace：   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Client.TenPayHttpClient.Signer.SHA256WithRSASigner.Sign(String message, String privateKey)
   at Senparc.Weixin.TenPayV3.TenPayHttpClient.TenPayHttpClient.GenerateAuthorizationHeader(HttpRequestMessage request)
   at Senparc.Weixin.TenPayV3.TenPayHttpClient.TenPayHttpClient.SendAsync[T](String url, Object data, Int32 timeOut, ApiRequestMethod requestMethod, Boolean checkSign, Func`1 createDefaultInstance)

[[[WeixinException]]]
[2022/12/16 02:12:33.9557]
[线程：10]
	WeixinException
	AccessTokenOrAppId：
	Message：获取 prepay_id 结果校验出错！{"prepay_id":null,"ResultCode":{"Success":false,"StateCode":null,"ErrorCode":null,"ErrorMessage":"系统找不到指定的文件。","Solution":null,"Additional":null},"VerifySignSuccess":null}
	StackTrace：

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：695443209@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
检查应用程序池的配置“加载用户配置文件”需要设置为 True。这个问题在 .NET Core 以后尤其要注意。

https://weixin.senparc.com/QA-20614
