### ISSUE TITLE
使用CoreMvc的WeixinResult，ContentResultExecutor.ExecuteAsync() - set_ContentType()抛异常

### ISSUE THREAD

**Issue by kchanlee** [JeffreySu/WeiXinMPSDK#796]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
使用CoreMvc的WeixinResult，ContentResultExecutor.ExecuteAsync() - set_ContentType()抛异常

看起来原因应该是：在`WeixinResult.ExecuteResult()`里写了一次`context.HttpContext.Response.Body`，随后调用`ContentResult.ExecuteResult()`，在那里面又写了一次`context.HttpContext.Response.Body`所导致。

异常详情如下：
```
System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.set_ContentType(String value)
   at Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.14.0
- [x] Senparc.Weixin.MP 版本：14.6.7
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] 其他模块：Senparc.Weixin.MP.CoreMvc: 1.4.0

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core 2.0.0

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
你用的解决方案文件（.sln）是哪个？

**Comment by kchanlee** [comment]
@JeffreySu 我用的是[Developer-FullDotNet branch](https://github.com/jeffreySu/WeiXinMPSDK/tree/Developer-FullDotNet) commit [c9600a61](https://github.com/JeffreySu/WeiXinMPSDK/commit/c9600a613e9f47a6ef41273c0466d16757097e2c)，直接拿Senparc.Weixin、Senparc.Weixin.MP、Senparc.Weixin.MP.CoreMvcExtension的源码来用，把它们的.csproj加到我的.sln里面。

**Comment by JeffreySu** [comment]
你的Action是怎么写的可以给我看一下吗？

**Comment by kchanlee** [comment]
@JeffreySu 
```
        [HttpPost]
        [ActionName("Index")]
        public async Task<ActionResult> Post(PostModel postModel)
        {
            if (!CheckSignature.Check(postModel.Signature, postModel.Timestamp, postModel.Nonce, _settings.WeChatToken))
            {
                _logger.LogError("Invalid Parameter received!");
                return Content("Invalid Parameter");
            }

            postModel.Token = _settings.WeChatToken;
            postModel.EncodingAESKey = _settings.WeChatEncodingAESKey;
            postModel.AppId = _settings.WeChatAppId;

            try
            {
                /**
                 * Some metheds/properties (e.g. Seek()) of Stream are not supported in Request.Body 
                 * but are invoked in WechatMessageHandler which cause exception. So we explicitly copy
                 * to a MemoryStream to avoid this.
                 */
                var stream = new MemoryStream();
                await Request.Body.CopyToAsync(stream);
                stream.Position = 0;

                var handler = new WechatMessageHandler(stream, postModel, _chatStore, _messagerHandlerLogger);
                await handler.ExecuteAsync();

                return new WeixinResult(handler);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Failed to process user's message.");
                return new WeixinResult(e.ToString());
            }
```

**Comment by JeffreySu** [comment]
参考 Senparc.Weixin.MP.CoreSample 项目中 WeixinController 里面，试试看这样写：


``` C#
            return new FixWeixinBugWeixinResult(messageHandler);//v0.8+
``

**Comment by kchanlee** [comment]
@JeffreySu 谢谢你的及时解答，我用以下方法解决问题了
```
return Content(handler.FinalResponseDocument.ToString(), "text/xml");
```

**Comment by kchanlee** [comment]
@JeffreySu 我觉得这应该算是个bug，希望能在后续版本修复

**Comment by JeffreySu** [comment]
非常感谢这么细心且给我们建议！
实际开发的话，你直接用我上面这个FixWeixinBugWeixinResult取代WeixinResult就行了，WeixinResult当时是用来解决其他问题的，但是基本上已经不在Demo里面出现了。

**Comment by JeffreySu** [comment]
看 \src\Senparc.Weixin.MP.Sample.vs2017\Senparc.Weixin.MP.Sample.vs2017.sln 这个是从.NET 4.5移植过来的Sample，可以正常运行。
