### ISSUE TITLE
System.NotSupportedException:“Specified method is not supported.”

### ISSUE THREAD

**Issue by LoveHikari** [JeffreySu/WeiXinMPSDK#810]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
stream.Seek(0L, SeekOrigin.Begin);报Specified method is not supported

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core 2.0

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
具体调用哪个方法的时候发生的？

**Comment by LoveHikari** [comment]
使用Senparc.Weixin.XmlUtility.XmlUtility.Convert(inputStream)时报的

**Comment by JeffreySu** [comment]
有详细的错误日志吗？查了一下，这个方法里面并没有用到Seek，是不是别的地方用到了？
另外，代码是最新的吧？

**Comment by JeffreySu** [comment]
查了一下，代码中没有完全一样的这一段代码：

```
stream.Seek(0L, SeekOrigin.Begin);
```

尤其是0L

**Comment by KevinPan** [comment]
我也遇到这个问题，是在
var messageHandler = new CustomMessageHandler(Request.Body, postModel, maxRecordCount);
这行代码调用基类构造函数的时候产生的

public CustomMessageHandler(Stream inputStream, PostModel postModel, int maxRecordCount = 0)
            : base(inputStream, postModel, maxRecordCount)

--------------------
以下是异常输出信息
System.NotSupportedException occurred
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.Seek(Int64 offset, SeekOrigin origin)
   at Senparc.Weixin.XmlUtility.XmlUtility.Convert(Stream stream)
   at Senparc.Weixin.MP.MessageHandlers.MessageHandler`1..ctor(Stream inputStream, PostModel postModel, Int32 maxRecordCount, DeveloperInfo developerInfo)
   at Coostone.App.Weixin.Utils.CustomMessageHandler..ctor(Stream inputStream, PostModel postModel, Int32 maxRecordCount) in D:\svn\diancang_master2\Weixin\Utils\CustomMessageHandle.cs:line 36
   at Coostone.App.Weixin.Controllers.WeixinController.Post(PostModel postModel) in D:\svn\diancang_master2\Weixin\Controllers\WeixinController.cs:line 59
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**Comment by KevinPan** [comment]
将Request.Body stream复制到一个新对象就不会有这个问题
var stream = new MemoryStream();
Request.Body.CopyTo(stream);
var messageHandler = new CustomMessageHandler(stream, postModel, maxRecordCount);

**Comment by lishewen** [comment]
Request.Body 取到的值为 null 是ASP.Net Core的执行机制导致的，去看看netcore的源码就知道了
并不是这个SDK导致的问题

**Comment by lishewen** [comment]
这里的最佳实践是对着SDK提供的 CoreSample 写代码，很多坑 SDK 的 Contributors 已经帮你们踩过了
