### ISSUE TITLE
使用Redis扩展报序列化错误

### ISSUE THREAD

**Issue by xfrogcn** [JeffreySu/WeiXinMPSDK#888]
##### 问题描述
在Startup中配置使用Redis缓存策略
`            RedisManager.ConfigurationOption = redisSection["Configuration"];
            CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisContainerCacheStrategy.Instance);
`
在调用获取Ticket接口时直接序列化报错
`var wxTicketResult = await Senparc.Weixin.MP.CommonAPIs.CommonApi.GetTicketAsync(appId, secret);
`

`System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at Senparc.Weixin.Cache.Redis.StackExchangeRedisExtensions.Serialize(Object o)
   at Senparc.Weixin.Cache.Redis.RedisObjectCacheStrategy.Update(String key, Object value, Boolean isFullKey)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.<>c__DisplayClass1_0.<Register>b__0()
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.Register(String appId, String appSecret, String name)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.<TryGetAccessTokenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<GetTicketAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
`

##### 发现问题的模块
- [x] Senparc.Weixin.MP 版本：14.8.0-beta2
- [x] Senparc.Weixin.Cache.Redis 版本：1.4.0-beta1

##### 模块对应的.net版本
- [ x] .net core

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境
- [X] Redis 版本：

**Comment by JeffreySu** [comment]
你是否有存在同一个redis服务了（或服务过）.net framework（如4.5）以及.net core的情况？

**Comment by xfrogcn** [comment]
@JeffreySu redis只有.NET Core使用，同一ASP.NET MVC Core应用中，MVC的redis扩展都能正常使用。

**Comment by xfrogcn** [comment]
感觉像是BindableBase 基类的PropertyChanged委托无法序列化引起的
    [Serializable]
    public abstract class BindableBase : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
.....
.NET Core中Binary序列化不支持委托类型
[https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core)

**Comment by JeffreySu** [comment]
确实有这个问题，这个问题的根本原因是由于.net core不支持委托的序列化造成的。

**Comment by JunLiangW** [comment]
楼上秦兄的解决方案是序列化成json. 也是微软推荐的方案.
As the nature of binary serialization allows the modification of private members inside an object and therefore changing the state of it, other serialization frameworks like JSON.NET which operate on the public API surface are recommended.

但还有个问题.就是反序列化时return JsonConvert.DeserializeObject<T>(json); 类型T如果是接口的话就报错. 必须在序列化成json时添加完整的类型说明.
public static byte[] Serialize(this object o)
{
            if (o == null)
            {
                return null;
            }
            JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings(); //应该可以用静态变量
            jsonSerializerSettings.TypeNameHandling = TypeNameHandling.All;   //序列化配置文件,注明需要完整的类型说明
            string json = JsonConvert.SerializeObject(o, jsonSerializerSettings);
            return Encoding.UTF8.GetBytes(json);
}

public static T Deserialize<T>(this byte[] stream)
{
            if (stream == null)
            {
                return default(T);
            }
            JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings();
            jsonSerializerSettings.TypeNameHandling = TypeNameHandling.All;
            string json = Encoding.UTF8.GetString(stream);
            return JsonConvert.DeserializeObject<T>(json, jsonSerializerSettings);  //直接从json中读取类型
}

**Comment by JeffreySu** [comment]
@JunLiangW 有没有这两种方法的性能测试报告？

**Comment by JunLiangW** [comment]
@JeffreySu 暂时没做测试

**Comment by JeffreySu** [comment]
@JunLiangW 上面用的微软说的JSON.NET的方法，也仍然不能解决包含委托的序列化问题吧？

**Comment by JunLiangW** [comment]
@JeffreySu 
json.net也就是Newtonsoft.Json库并不会序列化私有变量.
委托里应该是类似于对象的函数指针.我认为很难以序列化.而应该在实例化之后再处理.你代码也是这样做的.BaseContainerBag在对象初始化的时候自动添加了PropertyChanged事件响应了.
public BaseContainerBag()
{
        base.PropertyChanged += BaseContainerBag_PropertyChanged;
}

**Comment by JeffreySu** [comment]
当时使用委托是考虑到更新信息的便捷性问题，不然分布式缓存每次更新完属性，都要手动上传，太痛苦了。
