### ISSUE TITLE
在小程序里面获取微信运动步数，解密的时候，出这个错

### ISSUE THREAD

**Issue by xiluo** [JeffreySu/WeiXinMPSDK#911]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在小程序里面获取微信运动步数，解密的时候，出这个错
2017-11-06 13:44:40.1562 | Padding is invalid and cannot be removed. System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   at Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
   at HuiSoft.API.Controllers.User_StepController.Add(RnnEncryptData data) 
 <no type>.lambda_method => User_StepController.Add => LogHelper.Error 

##### 发现问题的模块
- [x] Senparc.Weixin.WxOpen 版本：

##### 模块对应的.net版本
- [x] .net 4.5

**Comment by xiluo** [comment]
encryptedData:"JF6Vi0XP1i68NlmCnqAs19YcId8GzrEUG7DX2dAKS/0LYadDtPcwbIqqGN/yrxqfO1nN6iDSquWJ112bsC8JaJ8TzSfZC/2IHG6vZ860ZJKVyhGKRmdYBM0O3feXW9MAugfIw+vnYs2V2HgX6TYI+1VVG/EBhlJt+0E1H3St1U1Dpi2jWknNthH/hGyXifh/MThsZ0CNIAhZse4XkJNbP+iJpz+yk+GY5ycKlldKmymrpLNKQJXqMczK63mzuKWAJcusnoRF1LEzzymUPKPdjHeVXSLf1SVODwFZaGcvH6zSLbr9xobL/Wk8yFOGvZa1jI/N5DeIYQsqQ6XZ7yOqRayshY0/7IvazFjwDHTNHHYGoq5WnGkPiOOFSMYE3o7bMAmYhQoiZFwtkZ8MjOUGxm9PeTSjn4Gb+UveHC7M+S/bkCZObL+2kS8xdPwl/OyGhQPnJsb+P6nSYb8ncQY6QoKrjpkb3RdCkWUHEGcGglZSYPqbShiawIMngZd+onzGj03B3PlfV0cjHbysMv7E/XOyxzZTkcqVU6RVYE0MpMKROseUhUsIyQuqeeM3pa2NIBejcUuI/FELXIrxy39EA+SwYqP2N7+3KWKFgxt48X4m2JxEOUi17ia/WXMqWMTTRwQJTr444qYpx0CUxdWgYPzoDIN+igrBkL//xOco2jfAnLoX6kWSNmZ/iJbgWu0ll7K5CD/5LEUHR7v/Sp7Sj21qGABUS4mf7AdZ6F3ywliPOIeuRldxjs1/7nysXy1lXg6eAgeGSOpIxvbcf94B65dt9R2oxPmpwfyTBCT5FPbWFxMDVh9bg2ENtsPYHICPcKqiuitKlRVnniqpCy7td0NUMmFW2bgEZdjbZ/+0GBDEsX85sMFUddbR0fbek6DfjK/y7ZNcNkHeqJv0TvExKeFY3G2ah6u5pPCbrtk/l/hi6JIa4vh31poG2/uXYchZyJBU8TtKrVi3TC37Sy8UJDvqjiih7Rxq5BPXG8pu7dRvmgXrkEX+IgAuuMhwI72OgqPk40ylzJ7fdlR21NtHsqT5sRboevA2Q/wtkBuKXyeS9PktjCsoqRDHbcQA9KlcqgYqHW3vKHdWMQZfotOYEsaaWSWbtHr3wXwTvAIi2Flfv659c6hfMuFMuyQhdY0FPXgoXYc4JIFzs+IOOWdiCtgBSzx6GjX7T9ITWxQUG/VOOUOeNTk/PkAYZ0DYcmScsxvxHDpZjUW9S9XPFKMTE5nchOUmexfPE7pR9MgzjCQJILLvs1kyZ0Q3YvZqYvGYSK5UAcDgWDJIl1bqe6CXHPVgT7wssYQ7eLpX7QZZ8rp+PPRd++GUxKyvfcUTkhrkzt0OyVs4wf/IfGmvvGsuLcOTk6UOrm+ESsDpWeo6qctXPLJemBvtqlZ6lXiwTzfZGr1Kz76KZOvrR0tLLBcM3eFyBeCFqK0wGefxcRDe88V5qqFUQqMAlgYyqTEl4UCAMfWO7a0jtaoLR5bVLNM7dtxonBSxogOyTUOeY/RWJ8k7f3LVRX3SQ0MUuD2S2mrZ2TeCkHjcPG6nZo+V2M9NHvijN0CFvv2s3S67KalwldEpH0u46XqED4NCzGgx4gkkRBes6k8rJjv4PQxp2DqkgQ=="
iv:"IdCn/M4uoj+qqF6xBKeqGQ=="

**Comment by JeffreySu** [comment]
@xiluo 没有SessionId没有办法测试，另外这个方法本身是好的。
另外具体的接口文档等最好按照issue默认格式发一下，方便我们跟踪，谢谢！

**Comment by JeffreySu** [comment]
@xiluo 如果能够提供更详细的信息，请 Reopen 这个 issue，谢谢！
